version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            # Add commands to run your tests here
      - persist_to_workspace:
          root: /workspace
          paths:
            - .  # This includes the entire project directory
  deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to Production
          command: |
            # Add deployment commands here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
