   name: Deploy to Staging

   on:
     push:
       branches:
         - main
   
   permissions:
      contents: read
      packages: write
   
   jobs:
     deploy:
       runs-on: ubuntu-latest
       environment: staging

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Deploy to GitHub Pages
           uses: JamesIves/github-pages-deploy-action@v4
           with:
             branch: gh-pages
             folder: .
